Repository Verssae/Invaders, pull requests merged in 2023-10, with the labels that each got.

#25 feat: added countdown design and changed bullet graphics
  .gitignore
  res/graphics
  res/invader_1.png
  res/invader_2.png
  res/invader_3.png
  res/invader_4.png
  src/engine/DrawManager.java
  src/screen/GameScreen.java
Labels: documentation, enhancement

#28 refactor: delete png files and add drawEntity method
  res/invader_1.png
  res/invader_2.png
  res/invader_3.png
  res/invader_4.png
  src/engine/DrawManager.java
Labels: enhancement

#49 feat: added a slowly changing color effect
  src/engine/DrawManager.java
  test/slowlyChangingColorsTest.java
Labels: enhancement

#58 feat: create a new shaped bullet
  res/graphics
  src/engine/DrawManager.java
  src/entity/BulletPool.java
  src/entity/BulletY.java
  src/entity/Entity.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: enhancement

#62 fix: changes related to BulletY
  src/effect/ShipEffect.java
  src/entity/BulletPool.java
  src/entity/Ship.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: bug, enhancement

#66 feat: added animated background effect and Game Over pop-up
  src/engine/Cooldown.java
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: bug, enhancement

#71 feat: add item designs
  requirements/CleanCode.md
  res/graphics
  src/engine/DrawManager.java
Labels: documentation, enhancement

#73 feat: modifying the loading screen
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  test/engine/DrawLoadingTest.java
Labels: enhancement

#83 feat: added a new death effect
  res/graphics
  src/engine/DrawManager.java
  src/entity/EnemyShip.java
Labels: bug, enhancement, help wanted

#85 feat: added effects to the Game Over screen
  res/graphics
  src/engine/DrawManager.java
  src/entity/Ship.java
  src/screen/GameScreen.java
Labels: enhancement

#88 feat: add coin parameter to GameState and change recovery algorithm
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/EnhanceManager.java
  src/engine/GameSettings.java
  src/engine/GameState.java
  src/entity/Coin.java
  src/entity/EnemyShipFormation.java
  src/entity/EnhanceStone.java
  src/screen/EnhanceScreen.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
  src/screen/SubMenuScreen.java
Labels: enhancement

#89 fix: comment out code that causes CI build failure
  requirements/CleanCode.md
  src/entity/EnemyShipFormation.java
Labels: bug, documentation

#92 docs: modified CleanCode.md
  requirements/CleanCode.md
Labels: documentation

#94 feat: add currency system about random boxes and monster drops
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/EnhanceManager.java
  src/engine/GameSettings.java
  src/engine/GameState.java
  src/engine/SkinBuyManager.java
  src/entity/EnhanceStone.java
  src/screen/EnhanceScreen.java
  src/screen/GameScreen.java
  src/screen/RandomBoxScreen.java
  src/screen/RandomRewardScreen.java
  src/screen/StoreScreen.java
Labels: enhancement

#102 docs: update implemented features to CleanCode.md
  requirements/CleanCode.md
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
Labels: documentation, help wanted

#108 feat: add itemManager and update gameState about randomBox, recovery
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/EnhanceManager.java
  src/engine/InputManager.java
  src/engine/ItemManager.java
  src/engine/SkinBuyManager.java
  src/entity/EnemyShip.java
  src/entity/EnemyShipFormation.java
  src/entity/Ship.java
  src/screen/EnhanceScreen.java
  src/screen/GameScreen.java
  src/screen/GameScreen_2P.java
  src/screen/RandomBoxScreen.java
  src/screen/RandomRewardScreen.java
  src/screen/RecoveryPaymentScreen.java
  src/screen/SkinStoreScreen.java
  src/screen/StoreScreen.java
  untitled/src/Main.java
  untitled1/src/Main.java
Labels: enhancement

#111 docs: final version of the CleanCode.md
  requirements/CleanCode.md
Labels: documentation

#119 feat: add Skin Purchase System and probability value adjustment
  requirements/currency.md
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/EnhanceManager.java
  src/engine/GameState.java
  src/engine/SkinBuyManager.java
  src/entity/Item.java
  src/screen/GameScreen.java
  src/screen/RandomBoxScreen.java
  src/screen/SkinStoreScreen.java
Labels: documentation, enhancement

#129 fix: bug caused by item probability
  src/entity/Item.java
Labels: bug
